# Generated by Django 5.2.6 on 2025-09-20 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Database name', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human readable name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Database description')),
                ('table_name', models.CharField(default='data', help_text='Main data table name', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, help_text='Database category (e.g., Real Estate, Automotive)', max_length=100)),
                ('total_records', models.IntegerField(default=0, help_text='Cached record count')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'display_name'],
                'permissions': [('can_view_owner_data', 'Can view owner database data'), ('can_export_owner_data', 'Can export owner database data'), ('can_manage_owner_databases', 'Can manage owner databases')],
            },
        ),
        migrations.CreateModel(
            name='OwnerDatabaseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owner.ownerdatabase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'database')},
            },
        ),
    ]
