# Generated by Django 5.2.6 on 2025-09-17 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_add_reference_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_leads', 'Can view leads'), ('can_add_leads', 'Can add leads'), ('can_change_leads', 'Can change leads'), ('can_delete_leads', 'Can delete leads'), ('can_assign_leads', 'Can assign leads'), ('can_convert_leads', 'Can convert leads')]},
        ),
        migrations.AlterModelOptions(
            name='leadpriority',
            options={'ordering': ['order', 'name'], 'permissions': [('can_manage_lead_priorities', 'Can manage lead priorities')], 'verbose_name_plural': 'Lead Priorities'},
        ),
        migrations.AlterModelOptions(
            name='leadsource',
            options={'ordering': ['name'], 'permissions': [('can_manage_lead_sources', 'Can manage lead sources')]},
        ),
        migrations.AlterModelOptions(
            name='leadstatus',
            options={'ordering': ['order', 'name'], 'permissions': [('can_manage_lead_statuses', 'Can manage lead statuses')], 'verbose_name_plural': 'Lead Statuses'},
        ),
        migrations.AlterModelOptions(
            name='leadtemperature',
            options={'ordering': ['order', 'name'], 'permissions': [('can_manage_lead_temperatures', 'Can manage lead temperatures')]},
        ),
        migrations.AlterModelOptions(
            name='leadtype',
            options={'ordering': ['name'], 'permissions': [('can_manage_lead_types', 'Can manage lead types')]},
        ),
        migrations.RemoveField(
            model_name='leadtemperature',
            name='score_max',
        ),
        migrations.RemoveField(
            model_name='leadtemperature',
            name='score_min',
        ),
        migrations.RemoveField(
            model_name='leadtype',
            name='color',
        ),
        migrations.AddField(
            model_name='leadtemperature',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.leadtype'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='preferred_contact_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('mobile', 'Mobile'), ('phone', 'Phone'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp')], default='mobile', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.leadpriority'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.leadstatus'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='temperature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.leadtemperature'),
        ),
        migrations.AlterField(
            model_name='leadpriority',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
        migrations.AlterField(
            model_name='leadpriority',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leadtemperature',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
        migrations.AlterField(
            model_name='leadtype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['mobile'], name='leads_lead_mobile_0244d4_idx'),
        ),
    ]
