# Generated by Django 5.2.6 on 2025-09-17 12:07

from django.db import migrations


def populate_reference_tables(apps, schema_editor):
    """Populate the new reference tables with default data"""
    LeadType = apps.get_model('leads', 'LeadType')
    LeadPriority = apps.get_model('leads', 'LeadPriority')
    LeadTemperature = apps.get_model('leads', 'LeadTemperature')
    
    # Create default lead types
    lead_types = [
        ('Buyer', 'Potential property buyer'),
        ('Seller', 'Property seller/landlord'),
        ('Renter', 'Looking for rental property'),
        ('Investor', 'Real estate investor'),
        ('Developer', 'Property developer'),
    ]
    
    for name, desc in lead_types:
        LeadType.objects.get_or_create(
            name=name,
            defaults={'description': desc}
        )
    
    # Create default priorities  
    priorities = [
        ('Low', 'Low priority lead', '#6c757d', 1),
        ('Medium', 'Medium priority lead', '#ffc107', 2),
        ('High', 'High priority lead', '#fd7e14', 3),
        ('Urgent', 'Urgent priority lead', '#dc3545', 4),
    ]
    
    for name, desc, color, order in priorities:
        LeadPriority.objects.get_or_create(
            name=name,
            defaults={'description': desc, 'color': color, 'order': order}
        )
    
    # Create default temperatures
    temperatures = [
        ('Cold', 'Not interested or unresponsive', '#6c757d', 1),
        ('Cool', 'Slightly interested', '#17a2b8', 2),
        ('Warm', 'Interested and engaged', '#ffc107', 3),
        ('Hot', 'Very interested, ready to buy', '#fd7e14', 4),
        ('Burning', 'Extremely hot lead, immediate action needed', '#dc3545', 5),
    ]
    
    for name, desc, color, order in temperatures:
        LeadTemperature.objects.get_or_create(
            name=name,
            defaults={
                'description': desc, 
                'color': color,
                'order': order
            }
        )


def reverse_migration(apps, schema_editor):
    """Reverse the migration if needed"""
    # Clear the new reference table data
    LeadType = apps.get_model('leads', 'LeadType')
    LeadPriority = apps.get_model('leads', 'LeadPriority') 
    LeadTemperature = apps.get_model('leads', 'LeadTemperature')
    
    LeadType.objects.all().delete()
    LeadPriority.objects.all().delete()
    LeadTemperature.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_options_alter_leadpriority_options_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_reference_tables, reverse_migration),
    ]
