# Generated by Django 5.2.6 on 2025-09-17 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_populate_status_source_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id_backup', models.UUIDField(blank=True, help_text='Backup of lead ID for deleted leads', null=True)),
                ('lead_name_backup', models.CharField(blank=True, help_text='Backup of lead name for deleted leads', max_length=200)),
                ('action', models.CharField(choices=[('create', 'Lead Created'), ('update', 'Lead Updated'), ('delete', 'Lead Deleted'), ('status_change', 'Status Changed'), ('assignment_change', 'Assignment Changed'), ('priority_change', 'Priority Changed'), ('temperature_change', 'Temperature Changed'), ('contact', 'Contact Made'), ('note_added', 'Note Added'), ('document_added', 'Document Added'), ('activity_added', 'Activity Added'), ('score_change', 'Score Changed'), ('conversion', 'Lead Converted'), ('restore', 'Lead Restored')], max_length=30)),
                ('description', models.TextField(help_text='Detailed description of the change')),
                ('field_name', models.CharField(blank=True, help_text='Name of changed field', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (JSON format)')),
                ('new_value', models.TextField(blank=True, help_text='New value (JSON format)')),
                ('user_name_backup', models.CharField(blank=True, help_text='Backup of username', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, help_text='Request tracking ID', max_length=100)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(default='web', help_text='Source of change (web, api, import, etc.)', max_length=50)),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object', max_length=50)),
                ('related_object_id', models.CharField(blank=True, help_text='ID of related object', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Contains sensitive information')),
                ('is_system_generated', models.BooleanField(default=False, help_text='Generated by system automation')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='leads.lead')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'permissions': [('can_view_lead_audits', 'Can view lead audit logs'), ('can_view_all_audits', 'Can view all audit logs'), ('can_export_audits', 'Can export audit logs'), ('can_manage_audits', 'Can manage audit settings'), ('can_delete_audits', 'Can delete audit logs')],
                'indexes': [models.Index(fields=['lead', 'timestamp'], name='leads_leada_lead_id_ab1aa5_idx'), models.Index(fields=['action', 'timestamp'], name='leads_leada_action_f04e29_idx'), models.Index(fields=['user', 'timestamp'], name='leads_leada_user_id_543a6a_idx'), models.Index(fields=['field_name', 'timestamp'], name='leads_leada_field_n_5c429a_idx'), models.Index(fields=['timestamp'], name='leads_leada_timesta_918056_idx'), models.Index(fields=['severity', 'timestamp'], name='leads_leada_severit_227978_idx')],
            },
        ),
    ]
