# Generated by Django 5.2.6 on 2025-09-18 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_leadaudit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLeadPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_checkbox', models.BooleanField(default=True)),
                ('show_name', models.BooleanField(default=True)),
                ('show_mobile', models.BooleanField(default=True)),
                ('show_email', models.BooleanField(default=True)),
                ('show_company', models.BooleanField(default=True)),
                ('show_status', models.BooleanField(default=True)),
                ('show_source', models.BooleanField(default=False)),
                ('show_priority', models.BooleanField(default=False)),
                ('show_temperature', models.BooleanField(default=False)),
                ('show_score', models.BooleanField(default=False)),
                ('show_assigned_to', models.BooleanField(default=True)),
                ('show_created_at', models.BooleanField(default=False)),
                ('show_last_contacted', models.BooleanField(default=False)),
                ('show_budget', models.BooleanField(default=False)),
                ('show_property_type', models.BooleanField(default=False)),
                ('show_actions', models.BooleanField(default=True)),
                ('column_order', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Lead Preference',
                'verbose_name_plural': 'User Lead Preferences',
            },
        ),
    ]
