# Generated by Django 5.2.6 on 2025-10-15 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_userleadpreferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(db_index=True, max_length=36)),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('call', 'Phone Call'), ('site_visit', 'Site Visit'), ('follow_up', 'Follow Up'), ('presentation', 'Presentation'), ('negotiation', 'Negotiation'), ('closing', 'Closing'), ('other', 'Other')], default='meeting', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('send_reminder', models.BooleanField(default=True)),
                ('reminder_minutes_before', models.PositiveIntegerField(default=30, help_text='Minutes before event to send reminder')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('outcome_notes', models.TextField(blank=True)),
                ('next_action', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_events', to=settings.AUTH_USER_MODEL)),
                ('attendees', models.ManyToManyField(blank=True, related_name='lead_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_datetime'],
                'permissions': [('can_view_all_events', 'Can view all events'), ('can_manage_all_events', 'Can manage all events')],
                'indexes': [models.Index(fields=['start_datetime', 'status'], name='leads_leade_start_d_1646e4_idx'), models.Index(fields=['assigned_to', 'start_datetime'], name='leads_leade_assigne_2c2f97_idx')],
            },
        ),
    ]
