#!/bin/bash

# Script to convert SQLite db.sqlite3 to MariaDB and deploy all databases
set -e

LOCAL_DB_USER="root"
LOCAL_DB_PASSWORD="zerocall"
MAIN_DB_NAME="glomart_crm"

echo "========================================="
echo "  Converting SQLite to MariaDB Locally"
echo "========================================="

# Check if glomart_crm database exists in MariaDB
if mysql -u "$LOCAL_DB_USER" -p"$LOCAL_DB_PASSWORD" -e "USE $MAIN_DB_NAME;" 2>/dev/null; then
    echo "✅ glomart_crm database already exists in MariaDB"
else
    echo "📦 Creating glomart_crm database in MariaDB..."
    mysql -u "$LOCAL_DB_USER" -p"$LOCAL_DB_PASSWORD" -e "CREATE DATABASE $MAIN_DB_NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
    echo "✅ Database created"
fi

# Update Django settings to use MariaDB locally
echo "⚙️  Updating local Django settings to use MariaDB..."
cp real_estate_crm/settings.py real_estate_crm/settings.py.backup-sqlite

# Create new settings with MariaDB configuration
cat > real_estate_crm/settings.py << 'EOF'
"""
Django settings for real_estate_crm project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4cow$muvk#-gxnnbvrzy80f5$$-)%s4(117e-89_q96s7aq7&1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.1.5', 'sys.glomartrealestates.com', '5.180.148.92']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'leads',
    'properties',  # Property management app
    'projects',    # Project management app
    'owner',       # Owner databases management app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'leads.middleware.AuditMiddleware',  # Add audit middleware
]

ROOT_URLCONF = 'real_estate_crm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'authentication.enhanced_context_processors.modules_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'real_estate_crm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'glomart_crm',
        'HOST': 'localhost',
        'USER': 'root',
        'PASSWORD': 'zerocall',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    },
    # MariaDB connection for owner databases
    'mariadb_owner': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': 'localhost',
        'USER': 'root',
        'PASSWORD': 'zerocall',
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "public",
]

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login/Logout URLs
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Context Processors
TEMPLATE_CONTEXT_PROCESSORS = [
    'authentication.context_processors.modules_processor',
]
EOF

echo "✅ Django settings updated to use MariaDB"

# Install required package for SQLite to MySQL migration
echo "📦 Installing sqlite3-to-mysql package..."
source venv/bin/activate
pip install sqlite3-to-mysql

# Convert SQLite to MariaDB
echo "🔄 Converting SQLite database to MariaDB..."
sqlite3mysql -f db.sqlite3 -d "$MAIN_DB_NAME" -u "$LOCAL_DB_USER" -p"$LOCAL_DB_PASSWORD" --mysql-insert-method INSERT

echo "✅ SQLite database converted to MariaDB successfully!"

# Run Django migrations to ensure schema is up to date
echo "🔄 Running Django migrations..."
python manage.py migrate

echo ""
echo "🎉 Local database conversion completed!"
echo "   • SQLite data migrated to glomart_crm MariaDB database"
echo "   • Django settings updated"
echo "   • Migrations applied"
echo ""
echo "Now ready to deploy all databases to production server..."
EOF