# Generated by Django 5.2.6 on 2025-09-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_userpropertypreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='primary_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
