# Generated by Django 5.2.6 on 2025-09-17 12:43

from django.db import migrations


def create_audit_module_and_permissions(apps, schema_editor):
    """Create audit module and its permissions"""
    Module = apps.get_model('authentication', 'Module')
    Permission = apps.get_model('authentication', 'Permission')
    
    # Create audit module
    audit_module, created = Module.objects.get_or_create(
        name='audit',
        defaults={
            'display_name': 'Audit & Logs',
            'icon': 'bi-shield-check',
            'url_name': 'audit_list',
            'order': 90,  # Place it near the end
            'is_active': True
        }
    )
    
    # Define audit permissions
    audit_permissions = [
        {
            'name': 'View Audit Logs',
            'code': 'view',
            'level': 1,
            'description': 'Can view audit logs for own actions'
        },
        {
            'name': 'View All Audit Logs',
            'code': 'view_all',
            'level': 2,
            'description': 'Can view all audit logs across the system'
        },
        {
            'name': 'Export Audit Logs',
            'code': 'export',
            'level': 3,
            'description': 'Can export audit logs to various formats'
        },
        {
            'name': 'Manage Audit Settings',
            'code': 'manage',
            'level': 4,
            'description': 'Can manage audit settings and purge old logs'
        }
    ]
    
    # Create permissions
    for perm_data in audit_permissions:
        Permission.objects.get_or_create(
            module=audit_module,
            code=perm_data['code'],
            defaults={
                'name': perm_data['name'],
                'level': perm_data['level'],
                'description': perm_data['description'],
                'is_active': True
            }
        )


def reverse_migration(apps, schema_editor):
    """Remove audit module and permissions"""
    Module = apps.get_model('authentication', 'Module')
    
    try:
        audit_module = Module.objects.get(name='audit')
        # This will cascade delete permissions due to foreign key
        audit_module.delete()
    except Module.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_audit_module_and_permissions, reverse_migration),
    ]
