# Generated by Django 5.2.6 on 2025-09-19 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_opportunities_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Filter name (e.g., 'Commercial Properties Only')", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('model_name', models.CharField(help_text="Model to filter (e.g., 'Property', 'Lead')", max_length=100)),
                ('filter_type', models.CharField(choices=[('include', 'Include Only'), ('exclude', 'Exclude'), ('conditional', 'Conditional')], default='include', max_length=50)),
                ('filter_conditions', models.JSONField(default=dict, help_text='JSON filter conditions')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Application order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.module')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_filters', to='authentication.profile')),
            ],
            options={
                'ordering': ['module', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DynamicDropdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Dropdown name (e.g., 'Property Types', 'Lead Sources')", max_length=100)),
                ('field_name', models.CharField(help_text='Field this dropdown is for', max_length=100)),
                ('source_model', models.CharField(help_text='Source model for dropdown options', max_length=100)),
                ('source_field', models.CharField(help_text='Field to use for option values', max_length=100)),
                ('display_field', models.CharField(help_text='Field to use for option labels', max_length=100)),
                ('allowed_values', models.JSONField(default=list, help_text='List of allowed values')),
                ('restricted_values', models.JSONField(default=list, help_text='List of restricted values')),
                ('filter_conditions', models.JSONField(default=dict, help_text='Additional filter conditions')),
                ('is_multi_select', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=100)),
                ('placeholder_text', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.module')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_dropdowns', to='authentication.profile')),
            ],
            options={
                'ordering': ['module', 'order', 'name'],
                'unique_together': {('profile', 'module', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='FieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text="Model name (e.g., 'Lead', 'Property')", max_length=100)),
                ('field_name', models.CharField(help_text="Field name (e.g., 'budget_max', 'property_type')", max_length=100)),
                ('can_view', models.BooleanField(default=True)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_filter', models.BooleanField(default=True, help_text='Can use this field for filtering data')),
                ('is_visible_in_list', models.BooleanField(default=True, help_text='Show in list views')),
                ('is_visible_in_detail', models.BooleanField(default=True, help_text='Show in detail views')),
                ('is_visible_in_forms', models.BooleanField(default=True, help_text='Show in create/edit forms')),
                ('show_condition', models.JSONField(blank=True, default=dict, help_text='JSON conditions for when to show field')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.module')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_permissions', to='authentication.profile')),
            ],
            options={
                'ordering': ['module', 'model_name', 'field_name'],
                'unique_together': {('profile', 'module', 'model_name', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='ProfileDataScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('scope_type', models.CharField(choices=[('all', 'All Data'), ('own', 'Own Data Only'), ('assigned', 'Assigned Data'), ('team', 'Team Data'), ('filtered', 'Filtered Data'), ('custom', 'Custom Query')], max_length=50)),
                ('scope_config', models.JSONField(default=dict, help_text='Configuration for data scope')),
                ('custom_query', models.TextField(blank=True, help_text='Custom Django ORM query')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.module')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_scopes', to='authentication.profile')),
            ],
            options={
                'ordering': ['module', 'order'],
                'unique_together': {('profile', 'module', 'scope_type')},
            },
        ),
    ]
